In [1]:
import numpy as np
import pandas as pd
import sklearn

train_docs = pd.read_csv("example_train.csv")
train_docs

Document      Class
0         Upgrad is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [2]:
# convert label to a numerical variable
train_docs['Class'] = train_docs.Class.map({'cinema':0, 'education':1})
train_docs

Document  Class
0         Upgrad is a great educational institution.      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [3]:
# convert the df to a numpy array
train_array = train_docs.values

# split X and y
X_train = train_array[:,0]
y_train  = train_array[:,1]
y_train = y_train.astype('int')# sklearn needs y as integers

print("X_train")
print(X_train)
print("y_train")
print(y_train)

X_train
['Upgrad is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
y_train
[1 1 1 0 0]


In [4]:
# createe an  object of CountVetorizer() class
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()

In [5]:
# Fit the vectorizer on training data
vec.fit(X_train)
vec.vocabulary_

{'upgrad': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

In [6]:
# Fit the vectorizer on training data again
# removing the stop words this time
vec = CountVectorizer(stop_words='english')
vec.fit(X_train)
vec.vocabulary_

{'upgrad': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [7]:
# printing features names
print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['cinema' 'depends' 'educational' 'ethics' 'good' 'great' 'greatness'
 'institution' 'movie' 'sholey' 'story' 'upgrad']
12


In [8]:
# another way of representing the features
X_transformed = vec.transform(X_train)
X_transformed

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [9]:
print(X_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [10]:
# converting transformed matrix back to an array
X_transformed.toarray()

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [11]:
# converting matrix to dataframe
pd.DataFrame(X_transformed.toarray(), columns=vec.get_feature_names_out())

cinema  depends  educational  ethics  good  great  greatness  institution  \
0       0        0            1       0     0      1          0            1   
1       0        1            1       1     0      0          1            0   
2       0        0            1       1     0      1          1            0   
3       1        0            0       0     0      1          0            0   
4       0        1            0       0     2      0          0            0   

   movie  sholey  story  upgrad  
0      0       0      0       1  
1      0       0      0       0  
2      0       0      1       0  
3      0       1      0       0  
4      1       0      1       0

In [12]:
# test data
test_docs = pd.read_csv("example_test.csv")
test_docs

Document      Class
0  very good educational institution  education

In [13]:
# convert Label to a numerical variable
test_docs['Class'] = test_docs.Class.map({'cinema':0, 'education':1})
test_docs

Document  Class
0  very good educational institution      1

In [14]:
# convert to numpy array
test_numpy_array = test_docs.values

# split into X and y
X_test = test_numpy_array[:,0]
y_test = test_numpy_array[:,1]

print("X_test")
print(X_test)
print("y_test")
print(y_test)

X_test
['very good educational institution']
y_test
[1]


In [15]:
X_test_transformed  = vec.transform(X_test)
X_test_transformed

<1x12 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [16]:
X_test = X_test_transformed.toarray()
X_test

array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

### vect.fit(train) learns the vocabulary of the training data


In [18]:
#building a multinomial NB model
from sklearn.naive_bayes import MultinomialNB

#instantiate NB class
mnb = MultinomialNB()
#fitting the model on training data
mnb.fit(X_transformed, y_train)

# note that we are using the sparse matrix X_transformed
# though you can also use the non-sparse version
# mnb.fit(X_transformed.toarray(), y_train)

# predicting probabilities of test data 
proba = mnb.predict_proba(X_test)

In [19]:
#probability of each class (test data)
print("probability of test document belonging to class CINEMA", proba[:,0])
print("probability of test document belonging to class EDUCATION", proba[:,1])

probability of test document belonging to class CINEMA [0.32808399]
probability of test document belonging to class EDUCATION [0.67191601]


In [20]:
from sklearn.naive_bayes import BernoulliNB

#instantiating bernoulli NB class
bnb = BernoulliNB()

#fitting the model
bnb.fit(X_transformed, y_train)

#also works
#bnb.fit(X_transformed.toarray(), y_train)

#predicting probability of test data
bnb.predict_proba(X_test)
prob_bnb = bnb.predict_proba(X_test)
prob_bnb

array([[0.2326374, 0.7673626]])