# NumPy

### NumPy is a python library use for wprking with arrays it also has a functions for working in domian of linear algebra, matrix and many more. NumPy stands for numerical python 

In [1]:
# import package
import numpy as np

In [2]:
print(np.__version__)

1.24.3


In [3]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
Z = np.arange(0,10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
Z = np.arange(0,10)
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [9]:
print(np.size(nz))

3


In [10]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)

[[0.93048674 0.06357978 0.7743635  0.31433191 0.88802143 0.74327828
  0.15477475 0.07649504 0.30201536 0.79779779]
 [0.46369116 0.58193912 0.23600938 0.95989081 0.13838104 0.23900977
  0.33030582 0.55343224 0.9103379  0.95417234]
 [0.72877807 0.04094978 0.55912075 0.88183666 0.28901974 0.52618762
  0.82203719 0.06524865 0.67568912 0.15093228]
 [0.73602339 0.03131524 0.56184072 0.21629807 0.25731908 0.80042558
  0.85560138 0.65463901 0.89866208 0.51715027]
 [0.11139356 0.18862013 0.07443166 0.60079951 0.32577452 0.24846161
  0.09495675 0.09289579 0.73070429 0.3827899 ]
 [0.74071266 0.71763671 0.60223687 0.9024831  0.66738926 0.83048935
  0.69185159 0.47270929 0.40314224 0.94551632]
 [0.06130468 0.78551026 0.18793016 0.00418818 0.12116325 0.86868713
  0.04404567 0.73388423 0.40560716 0.82099538]
 [0.34514966 0.54644598 0.25855821 0.87278671 0.52640223 0.23488497
  0.75088893 0.18941402 0.82789244 0.30206825]
 [0.32564905 0.66715782 0.36993165 0.03018461 0.14902646 0.42740982
  0.77416846

In [11]:
A = np.random.rand(10)

In [12]:
print(A.min())
print(A.max())

0.08459101758284249
0.9292660761599708


In [13]:
Z = np.ones((5,5))
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [15]:
Z = np.pad(Z, pad_width=1, mode='maximum')
print(Z)

[[1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1.]]


In [16]:
Z = np.random.random((2,2))
Z = np.pad(Z, pad_width=1, mode='edge')
print(Z)

[[0.92493821 0.92493821 0.33044079 0.33044079]
 [0.92493821 0.92493821 0.33044079 0.33044079]
 [0.47039692 0.47039692 0.79179037 0.79179037]
 [0.47039692 0.47039692 0.79179037 0.79179037]]


In [17]:
print(np.array(0) / np.array(0))

nan


C:\Users\Deevita\AppData\Local\Temp\ipykernel_7812\4120864939.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))


In [18]:
np.array(0)

array(0)

In [19]:
np.datetime64("today")

numpy.datetime64('2024-03-15')

In [20]:
Z = np.arange('2016-01', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31' '2016-02-01' '2016-02-02' '2016-02-03' '2016-02-04'
 '2016-02-05' '2016-02-06' '2016-02-07' '2016-02-08' '2016-02-09'
 '2016-02-10' '2016-02-11' '2016-02-12' '2016-02-13' '2016-02-14'
 '2016-02-15' '2016-02-16' '2016-02-17' '2016-02-18' '2016-02-19'
 '2016-02-20' '2016-02-21' '2016-02-22' '2016-02-23' '2016-02-24'
 '2016-02-25' '2016-02-26' '2016-02-27' '2016-02-28' '2016-02-29'
 '2016-03-01' '2016-03-02' '2016-03-03' '2016-03-04' '2016-03-05'
 '2016-03-06' '2016-03-07' '2016-03-08' '2016-03-09' '2016-03-10'
 '2016-03-11' '2016-03-12' '2016-03-13' '2016-03-14' '2016-03-15'
 '2016-03-

In [21]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)
type(Z)        

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


numpy.ndarray

In [22]:
Z = list(generate())
type(Z)

list

In [23]:
generate()

<generator object generate at 0x000001FF1D3AEB50>

In [24]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [25]:
Z = np.random.random(5)
Z.sort()
print(Z)

[0.12145836 0.19970152 0.70619781 0.88105958 0.99963151]


In [26]:
Z = np.arange(5)
np.add.reduce(Z)

10

In [27]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.37102775 0.36999285 0.36302885 0.93074386 0.62284146 0.85055104
 1.11643684 0.80052326 0.98604369 0.20009759]
[1.29606143 0.47673874 1.19519888 1.44903533 0.4692399  0.65118172
 0.59413508 0.69741382 0.10163997 1.35462161]


In [28]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.         0.65151036 0.10674601 0.5240345  0.77829687 0.48009895
 0.28661951 0.81970136 0.63234359 0.30580776]


In [29]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [30]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [31]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [35]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((20,20))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [36]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

89


In [37]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Deevita\AppData\Local\Temp\ipykernel_7812\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [38]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.73222961 0.82851375 0.47327044 0.71696477 0.3977404
  0.97501737 0.69133862 0.67540285 0.38081859]
 [0.73222961 0.         0.7450762  0.35418368 0.37383986 0.40412208
  0.25106433 0.37577503 0.5089549  0.46503027]
 [0.82851375 0.7450762  0.         0.50226002 0.37362645 0.53662137
  0.80551615 0.36933411 0.242829   0.91273988]
 [0.47327044 0.35418368 0.50226002 0.         0.25167753 0.07565422
  0.55125491 0.22823609 0.27160703 0.41688301]
 [0.71696477 0.37383986 0.37362645 0.25167753 0.         0.32348419
  0.45076745 0.0265438  0.1545121  0.64384325]
 [0.3977404  0.40412208 0.53662137 0.07565422 0.32348419 0.
  0.61616857 0.29899038 0.32106503 0.37644411]
 [0.97501737 0.25106433 0.80551615 0.55125491 0.45076745 0.61616857
  0.         0.46686395 0.60527551 0.71370525]
 [0.69133862 0.37577503 0.36933411 0.22823609 0.0265438  0.29899038
  0.46686395 0.         0.14036231 0.62595772]
 [0.67540285 0.5089549  0.242829   0.27160703 0.1545121  0.32106503
  0.60527551 0.140362

In [39]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[87 53 44 70 98 18 58 31 34 70]


In [40]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [41]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [42]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 2.49826573e-01 -5.65712283e-02  2.86079413e-01 -1.71919316e-01
  -2.76739599e-02  2.31301720e-01 -2.38220717e-01 -2.71660729e-02
  -5.26814081e-01  2.81157669e-01]
 [ 4.46197215e-01  6.05045799e-02 -1.38457198e-02 -1.79912165e-02
   3.55735488e-01 -4.47354647e-01 -2.68285201e-02 -2.94241281e-01
   1.21046089e-01 -1.83221988e-01]
 [ 2.02588396e-01 -2.92208546e-03  3.92010349e-01 -4.99841827e-01
   1.54318595e-01 -4.62952971e-04  2.73476089e-01 -1.64133803e-01
  -2.76567572e-01 -7.84651903e-02]
 [-3.12606131e-02 -1.17308147e-01 -3.65292991e-01 -1.26529696e-01
   2.45603338e-01  4.24052120e-01 -3.16648485e-01  2.75056816e-01
   2.79807545e-01 -2.67479887e-01]
 [-4.37152470e-01  3.99890003e-01 -6.19098328e-02  1.37968573e-01
   2.90485384e-01  1.82841706e-02 -2.84982778e-01  2.03415671e-01
  -4.61940038e-02 -2.19804718e-01]]


In [44]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


[[1 2 3]
 [0 3 3]
 [8 9 3]]
[[1 2 3]
 [0 3 3]
 [8 9 3]]


In [45]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5582494329493917


In [46]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [47]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [48]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 1. 2. 4. 4. 2. 1. 3. 4. 6.]
[ 5.  1.  3.  7.  7.  3.  1.  5.  7. 11.]


In [49]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [50]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64
